# Generated by Django 5.2.7 on 2025-11-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.IntegerField()),
                ('st_name', models.CharField(max_length=50)),
                ('st_email', models.EmailField(max_length=254, unique=True)),
                ('st_age', models.IntegerField()),
                ('st_gender', models.CharField(max_length=20)),
                ('st_mobile', models.BigIntegerField()),
                ('st_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_id', models.IntegerField()),
                ('teach_name', models.CharField(max_length=50)),
                ('teach_email', models.EmailField(max_length=254, unique=True)),
                ('teach_age', models.IntegerField()),
                ('teach_gender', models.CharField(max_length=20)),
                ('teach_mobile', models.BigIntegerField()),
                ('teach_address', models.CharField(max_length=100)),
            ],
        ),
    ]
